sudo: required
language: cpp
dist: trusty
notifications:
  email: false
compiler:
  - g++
 
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - gcc-8
before_install:
  - sudo apt-get update
  - pip install --user cpp-coveralls
  - git submodule update --init --recursive
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.16.tar.gz
  - tar xf libsodium-1.0.16.tar.gz
  - cd libsodium-1.0.16
  - ./configure
  - make && make check
  - sudo make install
  

install:
  - gem install coveralls-lcov
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
  - tar xf lcov_1.11.orig.tar.gz
  - sudo make -C lcov-1.11/ install

before_script:
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/bin/g++
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build
  - lcov --directory $PARENTDIR/build --zerocounters

script:
  - cd /home/travis/build/LjusFramework/ljus
  - cmake .
  - make tests.out
  - ./tests.out

after_success:
  - lcov --directory $PARENTDIR --capture --output-file coverage.info
  - lcov --remove coverage.info 'tests/*' 'other/*' 'cmake/*' '/usr/*' 'external/*' 'ljus/encryption/base64.h' --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov coverage.info --repo-token $REPO_TOKEN
