sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install libcurl-dev
  - git pull --recurse-submodules
  - make -C includes/argon2 && sudo make install -C includes/argon2
  - cd includes/nacl && ./do

script:
  - make test -j4
  - ./tests.out

after_success:
  - coveralls --exclude includes --exclude test --gcov-options '\-lp'