sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - git submodule update --init --recursive
  - make -C /home/travis/build/ErikPartridge/ljus/includes/argon2
  - sudo make install -C includes/argon2
  - ./includes/nacl/do

script:
  - make test -j4
  - ./tests.out

after_success:
  - coveralls --exclude includes --exclude test --gcov-options '\-lp'
