sudo: required
language: cpp
dist: trusty
notifications:
  email: false
compiler:
  - g++
 
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - http-server
            - g++-8
            - gcc-8

matrix:

  include:
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
         - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"


before_install:
  - ${MATRIX_EVAL}
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update
  - sudo apt-get install http-parser
  - sudo apt-get install libsodium-dev libuv-dev
  - git submodule update --init --recursive

before_script:
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/bin/g++
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd ..
  - cmake .
  - make tests.out
  - ./tests.out
