sudo: required
language: cpp
dist: trusty
notifications:
  email: false
compiler:
  - g++
 
addons:
    apt:
        sources:
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
        packages:
            - http-server
            - g++-8
            - gcc-8

before_install:
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update
  - sudo apt-get install libsodium-dev libuv-dev
  - git submodule update --init --recursive

before_script:
  - sudo rm /usr/bin/gcc
  - sudo rm /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/bin/g++
  - lcov --version
  - gcov --version
  - g++ --version
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build && cd $PARENTDIR/build

script:
  - cd ..
  - cmake .
  - make tests.out
  - ./tests.out
