sudo: required
language: cpp
compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  - sudo apt-get install libcurl-dev
  - git pull --recurse-submodules
  - cd $TRAVIS_BUILD_DIR/includes/argon2 && make && sudo make install
  - cd $TRAVIS_BUILD_DIR/includes/nacl && ./do

script:
  - make test -j4
  - ./tests.out

after_success:
  - coveralls --exclude includes --exclude test --gcov-options '\-lp'