# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cents/ljus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cents/ljus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cents/ljus/CMakeFiles /home/cents/ljus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cents/ljus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tests.out

# Build rule for target.
tests.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tests.out
.PHONY : tests.out

# fast build rule for target.
tests.out/fast:
	$(MAKE) -f CMakeFiles/tests.out.dir/build.make CMakeFiles/tests.out.dir/build
.PHONY : tests.out/fast

#=============================================================================
# Target rules for targets named files

# Build rule for target.
files: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 files
.PHONY : files

# fast build rule for target.
files/fast:
	$(MAKE) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/build
.PHONY : files/fast

#=============================================================================
# Target rules for targets named hash

# Build rule for target.
hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hash
.PHONY : hash

# fast build rule for target.
hash/fast:
	$(MAKE) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/build
.PHONY : hash/fast

#=============================================================================
# Target rules for targets named http

# Build rule for target.
http: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http
.PHONY : http

# fast build rule for target.
http/fast:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/build
.PHONY : http/fast

#=============================================================================
# Target rules for targets named config

# Build rule for target.
config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config
.PHONY : config

# fast build rule for target.
config/fast:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/build
.PHONY : config/fast

#=============================================================================
# Target rules for targets named crypt

# Build rule for target.
crypt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 crypt
.PHONY : crypt

# fast build rule for target.
crypt/fast:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/build
.PHONY : crypt/fast

#=============================================================================
# Target rules for targets named app.out

# Build rule for target.
app.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 app.out
.PHONY : app.out

# fast build rule for target.
app.out/fast:
	$(MAKE) -f CMakeFiles/app.out.dir/build.make CMakeFiles/app.out.dir/build
.PHONY : app.out/fast

#=============================================================================
# Target rules for targets named git_update

# Build rule for target.
git_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 git_update
.PHONY : git_update

# fast build rule for target.
git_update/fast:
	$(MAKE) -f CMakeFiles/git_update.dir/build.make CMakeFiles/git_update.dir/build
.PHONY : git_update/fast

#=============================================================================
# Target rules for targets named argon2

# Build rule for target.
argon2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 argon2
.PHONY : argon2

# fast build rule for target.
argon2/fast:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/build
.PHONY : argon2/fast

#=============================================================================
# Target rules for targets named pistache

# Build rule for target.
pistache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pistache
.PHONY : pistache

# fast build rule for target.
pistache/fast:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/build
.PHONY : pistache/fast

config.o: config.cpp.o

.PHONY : config.o

# target to build an object file
config.cpp.o:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.o
.PHONY : config.cpp.o

config.i: config.cpp.i

.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s

.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) -f CMakeFiles/config.dir/build.make CMakeFiles/config.dir/config.cpp.s
.PHONY : config.cpp.s

external/argon2/src/argon2.o: external/argon2/src/argon2.c.o

.PHONY : external/argon2/src/argon2.o

# target to build an object file
external/argon2/src/argon2.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/argon2.c.o
.PHONY : external/argon2/src/argon2.c.o

external/argon2/src/argon2.i: external/argon2/src/argon2.c.i

.PHONY : external/argon2/src/argon2.i

# target to preprocess a source file
external/argon2/src/argon2.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/argon2.c.i
.PHONY : external/argon2/src/argon2.c.i

external/argon2/src/argon2.s: external/argon2/src/argon2.c.s

.PHONY : external/argon2/src/argon2.s

# target to generate assembly for a file
external/argon2/src/argon2.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/argon2.c.s
.PHONY : external/argon2/src/argon2.c.s

external/argon2/src/bench.o: external/argon2/src/bench.c.o

.PHONY : external/argon2/src/bench.o

# target to build an object file
external/argon2/src/bench.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/bench.c.o
.PHONY : external/argon2/src/bench.c.o

external/argon2/src/bench.i: external/argon2/src/bench.c.i

.PHONY : external/argon2/src/bench.i

# target to preprocess a source file
external/argon2/src/bench.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/bench.c.i
.PHONY : external/argon2/src/bench.c.i

external/argon2/src/bench.s: external/argon2/src/bench.c.s

.PHONY : external/argon2/src/bench.s

# target to generate assembly for a file
external/argon2/src/bench.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/bench.c.s
.PHONY : external/argon2/src/bench.c.s

external/argon2/src/blake2/blake2b.o: external/argon2/src/blake2/blake2b.c.o

.PHONY : external/argon2/src/blake2/blake2b.o

# target to build an object file
external/argon2/src/blake2/blake2b.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/blake2/blake2b.c.o
.PHONY : external/argon2/src/blake2/blake2b.c.o

external/argon2/src/blake2/blake2b.i: external/argon2/src/blake2/blake2b.c.i

.PHONY : external/argon2/src/blake2/blake2b.i

# target to preprocess a source file
external/argon2/src/blake2/blake2b.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/blake2/blake2b.c.i
.PHONY : external/argon2/src/blake2/blake2b.c.i

external/argon2/src/blake2/blake2b.s: external/argon2/src/blake2/blake2b.c.s

.PHONY : external/argon2/src/blake2/blake2b.s

# target to generate assembly for a file
external/argon2/src/blake2/blake2b.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/blake2/blake2b.c.s
.PHONY : external/argon2/src/blake2/blake2b.c.s

external/argon2/src/core.o: external/argon2/src/core.c.o

.PHONY : external/argon2/src/core.o

# target to build an object file
external/argon2/src/core.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/core.c.o
.PHONY : external/argon2/src/core.c.o

external/argon2/src/core.i: external/argon2/src/core.c.i

.PHONY : external/argon2/src/core.i

# target to preprocess a source file
external/argon2/src/core.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/core.c.i
.PHONY : external/argon2/src/core.c.i

external/argon2/src/core.s: external/argon2/src/core.c.s

.PHONY : external/argon2/src/core.s

# target to generate assembly for a file
external/argon2/src/core.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/core.c.s
.PHONY : external/argon2/src/core.c.s

external/argon2/src/encoding.o: external/argon2/src/encoding.c.o

.PHONY : external/argon2/src/encoding.o

# target to build an object file
external/argon2/src/encoding.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/encoding.c.o
.PHONY : external/argon2/src/encoding.c.o

external/argon2/src/encoding.i: external/argon2/src/encoding.c.i

.PHONY : external/argon2/src/encoding.i

# target to preprocess a source file
external/argon2/src/encoding.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/encoding.c.i
.PHONY : external/argon2/src/encoding.c.i

external/argon2/src/encoding.s: external/argon2/src/encoding.c.s

.PHONY : external/argon2/src/encoding.s

# target to generate assembly for a file
external/argon2/src/encoding.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/encoding.c.s
.PHONY : external/argon2/src/encoding.c.s

external/argon2/src/genkat.o: external/argon2/src/genkat.c.o

.PHONY : external/argon2/src/genkat.o

# target to build an object file
external/argon2/src/genkat.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/genkat.c.o
.PHONY : external/argon2/src/genkat.c.o

external/argon2/src/genkat.i: external/argon2/src/genkat.c.i

.PHONY : external/argon2/src/genkat.i

# target to preprocess a source file
external/argon2/src/genkat.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/genkat.c.i
.PHONY : external/argon2/src/genkat.c.i

external/argon2/src/genkat.s: external/argon2/src/genkat.c.s

.PHONY : external/argon2/src/genkat.s

# target to generate assembly for a file
external/argon2/src/genkat.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/genkat.c.s
.PHONY : external/argon2/src/genkat.c.s

external/argon2/src/opt.o: external/argon2/src/opt.c.o

.PHONY : external/argon2/src/opt.o

# target to build an object file
external/argon2/src/opt.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/opt.c.o
.PHONY : external/argon2/src/opt.c.o

external/argon2/src/opt.i: external/argon2/src/opt.c.i

.PHONY : external/argon2/src/opt.i

# target to preprocess a source file
external/argon2/src/opt.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/opt.c.i
.PHONY : external/argon2/src/opt.c.i

external/argon2/src/opt.s: external/argon2/src/opt.c.s

.PHONY : external/argon2/src/opt.s

# target to generate assembly for a file
external/argon2/src/opt.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/opt.c.s
.PHONY : external/argon2/src/opt.c.s

external/argon2/src/ref.o: external/argon2/src/ref.c.o

.PHONY : external/argon2/src/ref.o

# target to build an object file
external/argon2/src/ref.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/ref.c.o
.PHONY : external/argon2/src/ref.c.o

external/argon2/src/ref.i: external/argon2/src/ref.c.i

.PHONY : external/argon2/src/ref.i

# target to preprocess a source file
external/argon2/src/ref.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/ref.c.i
.PHONY : external/argon2/src/ref.c.i

external/argon2/src/ref.s: external/argon2/src/ref.c.s

.PHONY : external/argon2/src/ref.s

# target to generate assembly for a file
external/argon2/src/ref.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/ref.c.s
.PHONY : external/argon2/src/ref.c.s

external/argon2/src/run.o: external/argon2/src/run.c.o

.PHONY : external/argon2/src/run.o

# target to build an object file
external/argon2/src/run.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/run.c.o
.PHONY : external/argon2/src/run.c.o

external/argon2/src/run.i: external/argon2/src/run.c.i

.PHONY : external/argon2/src/run.i

# target to preprocess a source file
external/argon2/src/run.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/run.c.i
.PHONY : external/argon2/src/run.c.i

external/argon2/src/run.s: external/argon2/src/run.c.s

.PHONY : external/argon2/src/run.s

# target to generate assembly for a file
external/argon2/src/run.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/run.c.s
.PHONY : external/argon2/src/run.c.s

external/argon2/src/test.o: external/argon2/src/test.c.o

.PHONY : external/argon2/src/test.o

# target to build an object file
external/argon2/src/test.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/test.c.o
.PHONY : external/argon2/src/test.c.o

external/argon2/src/test.i: external/argon2/src/test.c.i

.PHONY : external/argon2/src/test.i

# target to preprocess a source file
external/argon2/src/test.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/test.c.i
.PHONY : external/argon2/src/test.c.i

external/argon2/src/test.s: external/argon2/src/test.c.s

.PHONY : external/argon2/src/test.s

# target to generate assembly for a file
external/argon2/src/test.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/test.c.s
.PHONY : external/argon2/src/test.c.s

external/argon2/src/thread.o: external/argon2/src/thread.c.o

.PHONY : external/argon2/src/thread.o

# target to build an object file
external/argon2/src/thread.c.o:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/thread.c.o
.PHONY : external/argon2/src/thread.c.o

external/argon2/src/thread.i: external/argon2/src/thread.c.i

.PHONY : external/argon2/src/thread.i

# target to preprocess a source file
external/argon2/src/thread.c.i:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/thread.c.i
.PHONY : external/argon2/src/thread.c.i

external/argon2/src/thread.s: external/argon2/src/thread.c.s

.PHONY : external/argon2/src/thread.s

# target to generate assembly for a file
external/argon2/src/thread.c.s:
	$(MAKE) -f CMakeFiles/argon2.dir/build.make CMakeFiles/argon2.dir/external/argon2/src/thread.c.s
.PHONY : external/argon2/src/thread.c.s

external/pistache/src/client/client.o: external/pistache/src/client/client.cc.o

.PHONY : external/pistache/src/client/client.o

# target to build an object file
external/pistache/src/client/client.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/client/client.cc.o
.PHONY : external/pistache/src/client/client.cc.o

external/pistache/src/client/client.i: external/pistache/src/client/client.cc.i

.PHONY : external/pistache/src/client/client.i

# target to preprocess a source file
external/pistache/src/client/client.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/client/client.cc.i
.PHONY : external/pistache/src/client/client.cc.i

external/pistache/src/client/client.s: external/pistache/src/client/client.cc.s

.PHONY : external/pistache/src/client/client.s

# target to generate assembly for a file
external/pistache/src/client/client.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/client/client.cc.s
.PHONY : external/pistache/src/client/client.cc.s

external/pistache/src/common/cookie.o: external/pistache/src/common/cookie.cc.o

.PHONY : external/pistache/src/common/cookie.o

# target to build an object file
external/pistache/src/common/cookie.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/cookie.cc.o
.PHONY : external/pistache/src/common/cookie.cc.o

external/pistache/src/common/cookie.i: external/pistache/src/common/cookie.cc.i

.PHONY : external/pistache/src/common/cookie.i

# target to preprocess a source file
external/pistache/src/common/cookie.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/cookie.cc.i
.PHONY : external/pistache/src/common/cookie.cc.i

external/pistache/src/common/cookie.s: external/pistache/src/common/cookie.cc.s

.PHONY : external/pistache/src/common/cookie.s

# target to generate assembly for a file
external/pistache/src/common/cookie.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/cookie.cc.s
.PHONY : external/pistache/src/common/cookie.cc.s

external/pistache/src/common/description.o: external/pistache/src/common/description.cc.o

.PHONY : external/pistache/src/common/description.o

# target to build an object file
external/pistache/src/common/description.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/description.cc.o
.PHONY : external/pistache/src/common/description.cc.o

external/pistache/src/common/description.i: external/pistache/src/common/description.cc.i

.PHONY : external/pistache/src/common/description.i

# target to preprocess a source file
external/pistache/src/common/description.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/description.cc.i
.PHONY : external/pistache/src/common/description.cc.i

external/pistache/src/common/description.s: external/pistache/src/common/description.cc.s

.PHONY : external/pistache/src/common/description.s

# target to generate assembly for a file
external/pistache/src/common/description.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/description.cc.s
.PHONY : external/pistache/src/common/description.cc.s

external/pistache/src/common/http.o: external/pistache/src/common/http.cc.o

.PHONY : external/pistache/src/common/http.o

# target to build an object file
external/pistache/src/common/http.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http.cc.o
.PHONY : external/pistache/src/common/http.cc.o

external/pistache/src/common/http.i: external/pistache/src/common/http.cc.i

.PHONY : external/pistache/src/common/http.i

# target to preprocess a source file
external/pistache/src/common/http.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http.cc.i
.PHONY : external/pistache/src/common/http.cc.i

external/pistache/src/common/http.s: external/pistache/src/common/http.cc.s

.PHONY : external/pistache/src/common/http.s

# target to generate assembly for a file
external/pistache/src/common/http.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http.cc.s
.PHONY : external/pistache/src/common/http.cc.s

external/pistache/src/common/http_defs.o: external/pistache/src/common/http_defs.cc.o

.PHONY : external/pistache/src/common/http_defs.o

# target to build an object file
external/pistache/src/common/http_defs.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_defs.cc.o
.PHONY : external/pistache/src/common/http_defs.cc.o

external/pistache/src/common/http_defs.i: external/pistache/src/common/http_defs.cc.i

.PHONY : external/pistache/src/common/http_defs.i

# target to preprocess a source file
external/pistache/src/common/http_defs.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_defs.cc.i
.PHONY : external/pistache/src/common/http_defs.cc.i

external/pistache/src/common/http_defs.s: external/pistache/src/common/http_defs.cc.s

.PHONY : external/pistache/src/common/http_defs.s

# target to generate assembly for a file
external/pistache/src/common/http_defs.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_defs.cc.s
.PHONY : external/pistache/src/common/http_defs.cc.s

external/pistache/src/common/http_header.o: external/pistache/src/common/http_header.cc.o

.PHONY : external/pistache/src/common/http_header.o

# target to build an object file
external/pistache/src/common/http_header.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_header.cc.o
.PHONY : external/pistache/src/common/http_header.cc.o

external/pistache/src/common/http_header.i: external/pistache/src/common/http_header.cc.i

.PHONY : external/pistache/src/common/http_header.i

# target to preprocess a source file
external/pistache/src/common/http_header.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_header.cc.i
.PHONY : external/pistache/src/common/http_header.cc.i

external/pistache/src/common/http_header.s: external/pistache/src/common/http_header.cc.s

.PHONY : external/pistache/src/common/http_header.s

# target to generate assembly for a file
external/pistache/src/common/http_header.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_header.cc.s
.PHONY : external/pistache/src/common/http_header.cc.s

external/pistache/src/common/http_headers.o: external/pistache/src/common/http_headers.cc.o

.PHONY : external/pistache/src/common/http_headers.o

# target to build an object file
external/pistache/src/common/http_headers.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_headers.cc.o
.PHONY : external/pistache/src/common/http_headers.cc.o

external/pistache/src/common/http_headers.i: external/pistache/src/common/http_headers.cc.i

.PHONY : external/pistache/src/common/http_headers.i

# target to preprocess a source file
external/pistache/src/common/http_headers.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_headers.cc.i
.PHONY : external/pistache/src/common/http_headers.cc.i

external/pistache/src/common/http_headers.s: external/pistache/src/common/http_headers.cc.s

.PHONY : external/pistache/src/common/http_headers.s

# target to generate assembly for a file
external/pistache/src/common/http_headers.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/http_headers.cc.s
.PHONY : external/pistache/src/common/http_headers.cc.s

external/pistache/src/common/mime.o: external/pistache/src/common/mime.cc.o

.PHONY : external/pistache/src/common/mime.o

# target to build an object file
external/pistache/src/common/mime.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/mime.cc.o
.PHONY : external/pistache/src/common/mime.cc.o

external/pistache/src/common/mime.i: external/pistache/src/common/mime.cc.i

.PHONY : external/pistache/src/common/mime.i

# target to preprocess a source file
external/pistache/src/common/mime.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/mime.cc.i
.PHONY : external/pistache/src/common/mime.cc.i

external/pistache/src/common/mime.s: external/pistache/src/common/mime.cc.s

.PHONY : external/pistache/src/common/mime.s

# target to generate assembly for a file
external/pistache/src/common/mime.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/mime.cc.s
.PHONY : external/pistache/src/common/mime.cc.s

external/pistache/src/common/net.o: external/pistache/src/common/net.cc.o

.PHONY : external/pistache/src/common/net.o

# target to build an object file
external/pistache/src/common/net.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/net.cc.o
.PHONY : external/pistache/src/common/net.cc.o

external/pistache/src/common/net.i: external/pistache/src/common/net.cc.i

.PHONY : external/pistache/src/common/net.i

# target to preprocess a source file
external/pistache/src/common/net.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/net.cc.i
.PHONY : external/pistache/src/common/net.cc.i

external/pistache/src/common/net.s: external/pistache/src/common/net.cc.s

.PHONY : external/pistache/src/common/net.s

# target to generate assembly for a file
external/pistache/src/common/net.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/net.cc.s
.PHONY : external/pistache/src/common/net.cc.s

external/pistache/src/common/os.o: external/pistache/src/common/os.cc.o

.PHONY : external/pistache/src/common/os.o

# target to build an object file
external/pistache/src/common/os.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/os.cc.o
.PHONY : external/pistache/src/common/os.cc.o

external/pistache/src/common/os.i: external/pistache/src/common/os.cc.i

.PHONY : external/pistache/src/common/os.i

# target to preprocess a source file
external/pistache/src/common/os.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/os.cc.i
.PHONY : external/pistache/src/common/os.cc.i

external/pistache/src/common/os.s: external/pistache/src/common/os.cc.s

.PHONY : external/pistache/src/common/os.s

# target to generate assembly for a file
external/pistache/src/common/os.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/os.cc.s
.PHONY : external/pistache/src/common/os.cc.s

external/pistache/src/common/peer.o: external/pistache/src/common/peer.cc.o

.PHONY : external/pistache/src/common/peer.o

# target to build an object file
external/pistache/src/common/peer.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/peer.cc.o
.PHONY : external/pistache/src/common/peer.cc.o

external/pistache/src/common/peer.i: external/pistache/src/common/peer.cc.i

.PHONY : external/pistache/src/common/peer.i

# target to preprocess a source file
external/pistache/src/common/peer.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/peer.cc.i
.PHONY : external/pistache/src/common/peer.cc.i

external/pistache/src/common/peer.s: external/pistache/src/common/peer.cc.s

.PHONY : external/pistache/src/common/peer.s

# target to generate assembly for a file
external/pistache/src/common/peer.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/peer.cc.s
.PHONY : external/pistache/src/common/peer.cc.s

external/pistache/src/common/reactor.o: external/pistache/src/common/reactor.cc.o

.PHONY : external/pistache/src/common/reactor.o

# target to build an object file
external/pistache/src/common/reactor.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/reactor.cc.o
.PHONY : external/pistache/src/common/reactor.cc.o

external/pistache/src/common/reactor.i: external/pistache/src/common/reactor.cc.i

.PHONY : external/pistache/src/common/reactor.i

# target to preprocess a source file
external/pistache/src/common/reactor.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/reactor.cc.i
.PHONY : external/pistache/src/common/reactor.cc.i

external/pistache/src/common/reactor.s: external/pistache/src/common/reactor.cc.s

.PHONY : external/pistache/src/common/reactor.s

# target to generate assembly for a file
external/pistache/src/common/reactor.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/reactor.cc.s
.PHONY : external/pistache/src/common/reactor.cc.s

external/pistache/src/common/stream.o: external/pistache/src/common/stream.cc.o

.PHONY : external/pistache/src/common/stream.o

# target to build an object file
external/pistache/src/common/stream.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/stream.cc.o
.PHONY : external/pistache/src/common/stream.cc.o

external/pistache/src/common/stream.i: external/pistache/src/common/stream.cc.i

.PHONY : external/pistache/src/common/stream.i

# target to preprocess a source file
external/pistache/src/common/stream.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/stream.cc.i
.PHONY : external/pistache/src/common/stream.cc.i

external/pistache/src/common/stream.s: external/pistache/src/common/stream.cc.s

.PHONY : external/pistache/src/common/stream.s

# target to generate assembly for a file
external/pistache/src/common/stream.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/stream.cc.s
.PHONY : external/pistache/src/common/stream.cc.s

external/pistache/src/common/tcp.o: external/pistache/src/common/tcp.cc.o

.PHONY : external/pistache/src/common/tcp.o

# target to build an object file
external/pistache/src/common/tcp.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/tcp.cc.o
.PHONY : external/pistache/src/common/tcp.cc.o

external/pistache/src/common/tcp.i: external/pistache/src/common/tcp.cc.i

.PHONY : external/pistache/src/common/tcp.i

# target to preprocess a source file
external/pistache/src/common/tcp.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/tcp.cc.i
.PHONY : external/pistache/src/common/tcp.cc.i

external/pistache/src/common/tcp.s: external/pistache/src/common/tcp.cc.s

.PHONY : external/pistache/src/common/tcp.s

# target to generate assembly for a file
external/pistache/src/common/tcp.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/tcp.cc.s
.PHONY : external/pistache/src/common/tcp.cc.s

external/pistache/src/common/timer_pool.o: external/pistache/src/common/timer_pool.cc.o

.PHONY : external/pistache/src/common/timer_pool.o

# target to build an object file
external/pistache/src/common/timer_pool.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/timer_pool.cc.o
.PHONY : external/pistache/src/common/timer_pool.cc.o

external/pistache/src/common/timer_pool.i: external/pistache/src/common/timer_pool.cc.i

.PHONY : external/pistache/src/common/timer_pool.i

# target to preprocess a source file
external/pistache/src/common/timer_pool.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/timer_pool.cc.i
.PHONY : external/pistache/src/common/timer_pool.cc.i

external/pistache/src/common/timer_pool.s: external/pistache/src/common/timer_pool.cc.s

.PHONY : external/pistache/src/common/timer_pool.s

# target to generate assembly for a file
external/pistache/src/common/timer_pool.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/timer_pool.cc.s
.PHONY : external/pistache/src/common/timer_pool.cc.s

external/pistache/src/common/transport.o: external/pistache/src/common/transport.cc.o

.PHONY : external/pistache/src/common/transport.o

# target to build an object file
external/pistache/src/common/transport.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/transport.cc.o
.PHONY : external/pistache/src/common/transport.cc.o

external/pistache/src/common/transport.i: external/pistache/src/common/transport.cc.i

.PHONY : external/pistache/src/common/transport.i

# target to preprocess a source file
external/pistache/src/common/transport.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/transport.cc.i
.PHONY : external/pistache/src/common/transport.cc.i

external/pistache/src/common/transport.s: external/pistache/src/common/transport.cc.s

.PHONY : external/pistache/src/common/transport.s

# target to generate assembly for a file
external/pistache/src/common/transport.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/common/transport.cc.s
.PHONY : external/pistache/src/common/transport.cc.s

external/pistache/src/server/endpoint.o: external/pistache/src/server/endpoint.cc.o

.PHONY : external/pistache/src/server/endpoint.o

# target to build an object file
external/pistache/src/server/endpoint.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/endpoint.cc.o
.PHONY : external/pistache/src/server/endpoint.cc.o

external/pistache/src/server/endpoint.i: external/pistache/src/server/endpoint.cc.i

.PHONY : external/pistache/src/server/endpoint.i

# target to preprocess a source file
external/pistache/src/server/endpoint.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/endpoint.cc.i
.PHONY : external/pistache/src/server/endpoint.cc.i

external/pistache/src/server/endpoint.s: external/pistache/src/server/endpoint.cc.s

.PHONY : external/pistache/src/server/endpoint.s

# target to generate assembly for a file
external/pistache/src/server/endpoint.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/endpoint.cc.s
.PHONY : external/pistache/src/server/endpoint.cc.s

external/pistache/src/server/listener.o: external/pistache/src/server/listener.cc.o

.PHONY : external/pistache/src/server/listener.o

# target to build an object file
external/pistache/src/server/listener.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/listener.cc.o
.PHONY : external/pistache/src/server/listener.cc.o

external/pistache/src/server/listener.i: external/pistache/src/server/listener.cc.i

.PHONY : external/pistache/src/server/listener.i

# target to preprocess a source file
external/pistache/src/server/listener.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/listener.cc.i
.PHONY : external/pistache/src/server/listener.cc.i

external/pistache/src/server/listener.s: external/pistache/src/server/listener.cc.s

.PHONY : external/pistache/src/server/listener.s

# target to generate assembly for a file
external/pistache/src/server/listener.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/listener.cc.s
.PHONY : external/pistache/src/server/listener.cc.s

external/pistache/src/server/router.o: external/pistache/src/server/router.cc.o

.PHONY : external/pistache/src/server/router.o

# target to build an object file
external/pistache/src/server/router.cc.o:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/router.cc.o
.PHONY : external/pistache/src/server/router.cc.o

external/pistache/src/server/router.i: external/pistache/src/server/router.cc.i

.PHONY : external/pistache/src/server/router.i

# target to preprocess a source file
external/pistache/src/server/router.cc.i:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/router.cc.i
.PHONY : external/pistache/src/server/router.cc.i

external/pistache/src/server/router.s: external/pistache/src/server/router.cc.s

.PHONY : external/pistache/src/server/router.s

# target to generate assembly for a file
external/pistache/src/server/router.cc.s:
	$(MAKE) -f CMakeFiles/pistache.dir/build.make CMakeFiles/pistache.dir/external/pistache/src/server/router.cc.s
.PHONY : external/pistache/src/server/router.cc.s

ljus.o: ljus.cpp.o

.PHONY : ljus.o

# target to build an object file
ljus.cpp.o:
	$(MAKE) -f CMakeFiles/app.out.dir/build.make CMakeFiles/app.out.dir/ljus.cpp.o
.PHONY : ljus.cpp.o

ljus.i: ljus.cpp.i

.PHONY : ljus.i

# target to preprocess a source file
ljus.cpp.i:
	$(MAKE) -f CMakeFiles/app.out.dir/build.make CMakeFiles/app.out.dir/ljus.cpp.i
.PHONY : ljus.cpp.i

ljus.s: ljus.cpp.s

.PHONY : ljus.s

# target to generate assembly for a file
ljus.cpp.s:
	$(MAKE) -f CMakeFiles/app.out.dir/build.make CMakeFiles/app.out.dir/ljus.cpp.s
.PHONY : ljus.cpp.s

ljus/encryption/Crypt.o: ljus/encryption/Crypt.cpp.o

.PHONY : ljus/encryption/Crypt.o

# target to build an object file
ljus/encryption/Crypt.cpp.o:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/ljus/encryption/Crypt.cpp.o
.PHONY : ljus/encryption/Crypt.cpp.o

ljus/encryption/Crypt.i: ljus/encryption/Crypt.cpp.i

.PHONY : ljus/encryption/Crypt.i

# target to preprocess a source file
ljus/encryption/Crypt.cpp.i:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/ljus/encryption/Crypt.cpp.i
.PHONY : ljus/encryption/Crypt.cpp.i

ljus/encryption/Crypt.s: ljus/encryption/Crypt.cpp.s

.PHONY : ljus/encryption/Crypt.s

# target to generate assembly for a file
ljus/encryption/Crypt.cpp.s:
	$(MAKE) -f CMakeFiles/crypt.dir/build.make CMakeFiles/crypt.dir/ljus/encryption/Crypt.cpp.s
.PHONY : ljus/encryption/Crypt.cpp.s

ljus/files/Filesystem.o: ljus/files/Filesystem.cpp.o

.PHONY : ljus/files/Filesystem.o

# target to build an object file
ljus/files/Filesystem.cpp.o:
	$(MAKE) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/ljus/files/Filesystem.cpp.o
.PHONY : ljus/files/Filesystem.cpp.o

ljus/files/Filesystem.i: ljus/files/Filesystem.cpp.i

.PHONY : ljus/files/Filesystem.i

# target to preprocess a source file
ljus/files/Filesystem.cpp.i:
	$(MAKE) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/ljus/files/Filesystem.cpp.i
.PHONY : ljus/files/Filesystem.cpp.i

ljus/files/Filesystem.s: ljus/files/Filesystem.cpp.s

.PHONY : ljus/files/Filesystem.s

# target to generate assembly for a file
ljus/files/Filesystem.cpp.s:
	$(MAKE) -f CMakeFiles/files.dir/build.make CMakeFiles/files.dir/ljus/files/Filesystem.cpp.s
.PHONY : ljus/files/Filesystem.cpp.s

ljus/hash/Hash.o: ljus/hash/Hash.cpp.o

.PHONY : ljus/hash/Hash.o

# target to build an object file
ljus/hash/Hash.cpp.o:
	$(MAKE) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/ljus/hash/Hash.cpp.o
.PHONY : ljus/hash/Hash.cpp.o

ljus/hash/Hash.i: ljus/hash/Hash.cpp.i

.PHONY : ljus/hash/Hash.i

# target to preprocess a source file
ljus/hash/Hash.cpp.i:
	$(MAKE) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/ljus/hash/Hash.cpp.i
.PHONY : ljus/hash/Hash.cpp.i

ljus/hash/Hash.s: ljus/hash/Hash.cpp.s

.PHONY : ljus/hash/Hash.s

# target to generate assembly for a file
ljus/hash/Hash.cpp.s:
	$(MAKE) -f CMakeFiles/hash.dir/build.make CMakeFiles/hash.dir/ljus/hash/Hash.cpp.s
.PHONY : ljus/hash/Hash.cpp.s

ljus/http/LjusEndpoint.o: ljus/http/LjusEndpoint.cpp.o

.PHONY : ljus/http/LjusEndpoint.o

# target to build an object file
ljus/http/LjusEndpoint.cpp.o:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusEndpoint.cpp.o
.PHONY : ljus/http/LjusEndpoint.cpp.o

ljus/http/LjusEndpoint.i: ljus/http/LjusEndpoint.cpp.i

.PHONY : ljus/http/LjusEndpoint.i

# target to preprocess a source file
ljus/http/LjusEndpoint.cpp.i:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusEndpoint.cpp.i
.PHONY : ljus/http/LjusEndpoint.cpp.i

ljus/http/LjusEndpoint.s: ljus/http/LjusEndpoint.cpp.s

.PHONY : ljus/http/LjusEndpoint.s

# target to generate assembly for a file
ljus/http/LjusEndpoint.cpp.s:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusEndpoint.cpp.s
.PHONY : ljus/http/LjusEndpoint.cpp.s

ljus/http/LjusHandler.o: ljus/http/LjusHandler.cpp.o

.PHONY : ljus/http/LjusHandler.o

# target to build an object file
ljus/http/LjusHandler.cpp.o:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusHandler.cpp.o
.PHONY : ljus/http/LjusHandler.cpp.o

ljus/http/LjusHandler.i: ljus/http/LjusHandler.cpp.i

.PHONY : ljus/http/LjusHandler.i

# target to preprocess a source file
ljus/http/LjusHandler.cpp.i:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusHandler.cpp.i
.PHONY : ljus/http/LjusHandler.cpp.i

ljus/http/LjusHandler.s: ljus/http/LjusHandler.cpp.s

.PHONY : ljus/http/LjusHandler.s

# target to generate assembly for a file
ljus/http/LjusHandler.cpp.s:
	$(MAKE) -f CMakeFiles/http.dir/build.make CMakeFiles/http.dir/ljus/http/LjusHandler.cpp.s
.PHONY : ljus/http/LjusHandler.cpp.s

tests/test.o: tests/test.cpp.o

.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) -f CMakeFiles/tests.out.dir/build.make CMakeFiles/tests.out.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i

.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) -f CMakeFiles/tests.out.dir/build.make CMakeFiles/tests.out.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s

.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) -f CMakeFiles/tests.out.dir/build.make CMakeFiles/tests.out.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tests.out"
	@echo "... files"
	@echo "... hash"
	@echo "... http"
	@echo "... config"
	@echo "... crypt"
	@echo "... app.out"
	@echo "... git_update"
	@echo "... argon2"
	@echo "... pistache"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... external/argon2/src/argon2.o"
	@echo "... external/argon2/src/argon2.i"
	@echo "... external/argon2/src/argon2.s"
	@echo "... external/argon2/src/bench.o"
	@echo "... external/argon2/src/bench.i"
	@echo "... external/argon2/src/bench.s"
	@echo "... external/argon2/src/blake2/blake2b.o"
	@echo "... external/argon2/src/blake2/blake2b.i"
	@echo "... external/argon2/src/blake2/blake2b.s"
	@echo "... external/argon2/src/core.o"
	@echo "... external/argon2/src/core.i"
	@echo "... external/argon2/src/core.s"
	@echo "... external/argon2/src/encoding.o"
	@echo "... external/argon2/src/encoding.i"
	@echo "... external/argon2/src/encoding.s"
	@echo "... external/argon2/src/genkat.o"
	@echo "... external/argon2/src/genkat.i"
	@echo "... external/argon2/src/genkat.s"
	@echo "... external/argon2/src/opt.o"
	@echo "... external/argon2/src/opt.i"
	@echo "... external/argon2/src/opt.s"
	@echo "... external/argon2/src/ref.o"
	@echo "... external/argon2/src/ref.i"
	@echo "... external/argon2/src/ref.s"
	@echo "... external/argon2/src/run.o"
	@echo "... external/argon2/src/run.i"
	@echo "... external/argon2/src/run.s"
	@echo "... external/argon2/src/test.o"
	@echo "... external/argon2/src/test.i"
	@echo "... external/argon2/src/test.s"
	@echo "... external/argon2/src/thread.o"
	@echo "... external/argon2/src/thread.i"
	@echo "... external/argon2/src/thread.s"
	@echo "... external/pistache/src/client/client.o"
	@echo "... external/pistache/src/client/client.i"
	@echo "... external/pistache/src/client/client.s"
	@echo "... external/pistache/src/common/cookie.o"
	@echo "... external/pistache/src/common/cookie.i"
	@echo "... external/pistache/src/common/cookie.s"
	@echo "... external/pistache/src/common/description.o"
	@echo "... external/pistache/src/common/description.i"
	@echo "... external/pistache/src/common/description.s"
	@echo "... external/pistache/src/common/http.o"
	@echo "... external/pistache/src/common/http.i"
	@echo "... external/pistache/src/common/http.s"
	@echo "... external/pistache/src/common/http_defs.o"
	@echo "... external/pistache/src/common/http_defs.i"
	@echo "... external/pistache/src/common/http_defs.s"
	@echo "... external/pistache/src/common/http_header.o"
	@echo "... external/pistache/src/common/http_header.i"
	@echo "... external/pistache/src/common/http_header.s"
	@echo "... external/pistache/src/common/http_headers.o"
	@echo "... external/pistache/src/common/http_headers.i"
	@echo "... external/pistache/src/common/http_headers.s"
	@echo "... external/pistache/src/common/mime.o"
	@echo "... external/pistache/src/common/mime.i"
	@echo "... external/pistache/src/common/mime.s"
	@echo "... external/pistache/src/common/net.o"
	@echo "... external/pistache/src/common/net.i"
	@echo "... external/pistache/src/common/net.s"
	@echo "... external/pistache/src/common/os.o"
	@echo "... external/pistache/src/common/os.i"
	@echo "... external/pistache/src/common/os.s"
	@echo "... external/pistache/src/common/peer.o"
	@echo "... external/pistache/src/common/peer.i"
	@echo "... external/pistache/src/common/peer.s"
	@echo "... external/pistache/src/common/reactor.o"
	@echo "... external/pistache/src/common/reactor.i"
	@echo "... external/pistache/src/common/reactor.s"
	@echo "... external/pistache/src/common/stream.o"
	@echo "... external/pistache/src/common/stream.i"
	@echo "... external/pistache/src/common/stream.s"
	@echo "... external/pistache/src/common/tcp.o"
	@echo "... external/pistache/src/common/tcp.i"
	@echo "... external/pistache/src/common/tcp.s"
	@echo "... external/pistache/src/common/timer_pool.o"
	@echo "... external/pistache/src/common/timer_pool.i"
	@echo "... external/pistache/src/common/timer_pool.s"
	@echo "... external/pistache/src/common/transport.o"
	@echo "... external/pistache/src/common/transport.i"
	@echo "... external/pistache/src/common/transport.s"
	@echo "... external/pistache/src/server/endpoint.o"
	@echo "... external/pistache/src/server/endpoint.i"
	@echo "... external/pistache/src/server/endpoint.s"
	@echo "... external/pistache/src/server/listener.o"
	@echo "... external/pistache/src/server/listener.i"
	@echo "... external/pistache/src/server/listener.s"
	@echo "... external/pistache/src/server/router.o"
	@echo "... external/pistache/src/server/router.i"
	@echo "... external/pistache/src/server/router.s"
	@echo "... ljus.o"
	@echo "... ljus.i"
	@echo "... ljus.s"
	@echo "... ljus/encryption/Crypt.o"
	@echo "... ljus/encryption/Crypt.i"
	@echo "... ljus/encryption/Crypt.s"
	@echo "... ljus/files/Filesystem.o"
	@echo "... ljus/files/Filesystem.i"
	@echo "... ljus/files/Filesystem.s"
	@echo "... ljus/hash/Hash.o"
	@echo "... ljus/hash/Hash.i"
	@echo "... ljus/hash/Hash.s"
	@echo "... ljus/http/LjusEndpoint.o"
	@echo "... ljus/http/LjusEndpoint.i"
	@echo "... ljus/http/LjusEndpoint.s"
	@echo "... ljus/http/LjusHandler.o"
	@echo "... ljus/http/LjusHandler.i"
	@echo "... ljus/http/LjusHandler.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

